FROM mambaorg/micromamba:2.3.2

USER root
COPY environment-docking.yml /tmp/environment-docking.yml
RUN micromamba create -y -n amr-unbind-docking -f /tmp/environment-docking.yml && \
    micromamba clean --all --yes

COPY . /opt/amr-unbind
WORKDIR /opt/amr-unbind
ENV PATH=/opt/conda/envs/amr-unbind-docking/bin:$PATH
EXPOSE 8501
# ENTRYPOINT ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
